name: flutter_app
description: App Movil para Uso de Buses Publicos

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  path_provider: ^1.1.0

  firebase_core: ^0.3.0+2
  cloud_firestore: ^0.9.0+2

  rxdart: ^0.20.0

  geoflutterfire: ^2.0.2

  location: 1.4.1
  google_maps_flutter: 0.2.0+2
  firebase_database:
  device_id:

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
  - assets/backround.jpg
  - assets/LaPazBusLogo.png

